# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

permissions:
  contents: read

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/ruff-action@v3

  formatter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Check formatting
        uses: astral-sh/ruff-action@v3
        with:
          args: format --check

      - name: Check sorting of imports
        uses: astral-sh/ruff-action@v3
        with:
          args: check --select I

  type-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Run type checks with mypy
        run: |
          uvx mypy src/anls_star


  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deps-resolution: ["default", "lowest-direct"]
        experimental: [false]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - uses: actions/checkout@v6
        with:
          lfs: false

      - name: Install uv and set the Python version ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install Python and dependencies
        run: |
          UV_SYNC_ARGS="--group test"

          if [ "${{ matrix.deps-resolution }}" != "default" ]; then
            UV_SYNC_ARGS="$UV_SYNC_ARGS --resolution=${{ matrix.deps-resolution }}"
          fi

          if ${{ matrix.experimental }}; then
            echo "Installing dependencies by overriding requires-python and syncing without relying on lockfile (experimental mode)"
            
            PYPROJECT_FILE="pyproject.toml"
            NEW_PYTHON_REQUIREMENT="~=${{ matrix.python-version }}.0"

            if sed -i "s/^\(requires-python\s*=\s*\).*$/requires-python = \"$NEW_PYTHON_REQUIREMENT\"/I" "$PYPROJECT_FILE"; then
              echo "Successfully updated requires-python in $PYPROJECT_FILE."
            fi
          fi

          if [ "${{ matrix.experimental }}" != "true" ] && [ "${{ matrix.deps-resolution }}" = "default" ]; then
            UV_SYNC_ARGS="$UV_SYNC_ARGS --locked"
          fi

          echo "Running: uv sync $UV_SYNC_ARGS"
          uv sync $UV_SYNC_ARGS
        continue-on-error: ${{ matrix.experimental }}

      - name: Test with pytest
        run: |
          uv run --no-sync pytest --durations=40
        continue-on-error: ${{ matrix.experimental }}
